from typing import List

CSV_COLUMNS: List[str] = [
    "RECORD NO",
    "IMAGE NAME",
    "CUSTOMER NAME",
    "EMAIL ADDRESS",
    "RES_ADDRESS",
    "CITY_1",
    "STATE_1",
    "ZIP_1",
    "PH_NO1",
    "COUNTRY_1",
    "SEX_1",
    "D BIRTH",
    "HEIGHT",
    "WEIGHT",
    "BLOOD GP",
    "BILLER NAME",
    "SHIPPER NAME",
    "CITY_2",
    "STATE_2",
    "ZIP_2",
    "COUNTRY_2",
    "PH_NO2",
    "ALCOHOLIC",
    "SMOKER",
    "PAST SURG",
    "DIABETIC",
    "ALLERGIESED",
    "POLICY NO",
    "D_B_LIFE_ASSURE",
    "P_INST",
    "NAME_P_HOLDER",
    "STM NAME",
    "STM CODE",
    "DOB",
    "SEX_2",
    "CARD NAME",
    "MEDICINE",
    "DOSAGE",
    "TABLETS",
    "PILL RATE",
    "COST",
    "SHIPPING CO",
    "TOTAL AMT"
]
